{{- if .Values.cdnLogsCollector.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-logging.cdnLogsCollector.fullname" . }}-metrics
  labels:
    {{- include "lagoon-logging.cdnLogsCollector.labels" . | nindent 4 }}
  {{- with .Values.cdnLogsCollector.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cdnLogsCollector.metrics.service.type }}
  selector:
    {{- include "lagoon-logging.cdnLogsCollector.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.cdnLogsCollector.metrics.service.port }}
    name: metrics
    protocol: TCP
    targetPort: metrics
{{- end }}
