apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-ingress-class: nginx
    kubernetes.io/tls-acme: "true"
    meta.helm.sh/release-name: lagoon-core
    meta.helm.sh/release-namespace: lagoon-core
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: lagoon-core-oauth2proxy
  namespace: lagoon-core
spec:
  ingressClassName: nginx
  rules:
  - host: lagoon-oauth2proxy.172.18.0.240.nip.io
    http:
      paths:
      - backend:
          service:
            name: lagoon-core-oauth2proxy
            port:
              number: 4180
        path: /oauth2
        pathType: Prefix
      - backend:
          service:
            name: lagoon-core-oauth2proxy
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - lagoon-oauth2proxy.172.18.0.240.nip.io
    secretName: oauth2proxy-tls

