{{- if .Values.oauth2proxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-core.oauth2proxy.fullname" . }}
  labels:
    {{- include "lagoon-core.oauth2proxy.labels" . | nindent 4 }}
spec:
{{- if not .Values.oauth2proxy.autoscaling.enabled }}
  replicas: {{ .Values.oauth2proxy.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "lagoon-core.oauth2proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
    {{- with .Values.oauth2proxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-core.oauth2proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (coalesce .Values.oauth2proxy.podSecurityContext .Values.podSecurityContext) | nindent 8 }}
      volumes:
        - name: keycloak-ca-volume
          secret:
            secretName: lagoon-test-secret
      containers:
      - name: oauth2proxy
        securityContext:
          {{- toYaml .Values.oauth2proxy.securityContext | nindent 10 }}
        image: "{{ .Values.oauth2proxy.image.repository }}:{{ coalesce .Values.oauth2proxy.image.tag .Values.imageTag "latest" }}"
        imagePullPolicy: {{ .Values.oauth2proxy.image.pullPolicy }}
        env:
        - name: OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION
          value: "true"
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.oauth2proxy.fullname" . }}
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.oauth2proxy.fullname" . }}
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.oauth2proxy.fullname" . }}
              key: OAUTH2_PROXY_COOKIE_SECRET
        - name: OAUTH2_PROXY_PROVIDER
          value: "keycloak-oidc"
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "https://172.18.0.240.nip.io/oauth2/callback"
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: "0.0.0.0:4180"
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://nginx:8080"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: "https://lagoon-keycloak.172.18.0.240.nip.io/auth/realms/lagoon"
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"
        - name: OAUTH2_PROXY_COOKIE_SECURE
          value: "false"
        - name: OAUTH2_PROXY_SCOPE
          value: "openid profile email"
        - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
          value: "S256"
        - name: OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST
          value: "true"
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_REVERSE_PROXY
          value: "true"
        - name: OAUTH2_PROXY_PROVIDER_CA_FILE
          value: "/etc/ssl/certs/keycloak/ca.crt"
      {{- range $key, $val := .Values.oauth2proxy.additionalEnvs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
      {{- end }}
        volumeMounts:
          - name: keycloak-ca-volume
            mountPath: /etc/ssl/certs/keycloak
            readOnly: true
        ports:
        - name: http-4180
          containerPort: 4180
        livenessProbe:
          httpGet:
            path: /
            port: http-4180
        readinessProbe:
          httpGet:
            path: /
            port: http-4180
        resources:
        {{- toYaml .Values.oauth2proxy.resources | nindent 10 }}
      {{- with .Values.oauth2proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "lagoon-core.name" . }}
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - {{ include "lagoon-core.oauth2proxy.fullname" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- with .Values.oauth2proxy.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oauth2proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
