apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lagoon-remote.dockerHost.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lagoon-remote.dockerHost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dockerHost.replicaCount }}
  serviceName: docker-host
  selector:
    matchLabels:
      {{- include "lagoon-remote.dockerHost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lagoon-remote.dockerHost.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dockerHost.serviceAccount.create }}
      serviceAccountName: {{ include "lagoon-remote.dockerHost.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.dockerHost.podSecurityContext | nindent 8 }}
      containers:
      - name: docker-host
        securityContext:
          {{- toYaml .Values.dockerHost.securityContext | nindent 10 }}
        image: "{{ .Values.dockerHost.image.repository }}:{{ coalesce .Values.dockerHost.image.tag .Values.imageTag "latest" }}"
        imagePullPolicy: {{ .Values.dockerHost.image.pullPolicy }}
        env:
        {{- with .Values.extraEnvs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.dockerHost.httpProxy }}
        - name: HTTP_PROXY
          value: {{ . | quote }}
        - name: http_proxy
          value: {{ . | quote }}
        {{- end }}
        {{- with .Values.dockerHost.httpsProxy }}
        - name: HTTPS_PROXY
          value: {{ . | quote }}
        - name: https_proxy
          value: {{ . | quote }}
        {{- end }}
        {{- with .Values.dockerHost.noProxy }}
        - name: NO_PROXY
          value: {{ . | quote }}
        - name: no_proxy
          value: {{ . | quote }}
        {{- end }}
        - name: DOCKER_HOST
          value: localhost
        - name: REGISTRY
          value: {{ .Values.dockerHost.registry | quote }}
        - name: REPOSITORY_TO_UPDATE
          value: {{ .Values.dockerHost.repositoryToUpdate | quote }}
        - name: PRUNE_IMAGES_UNTIL
          value: {{ .Values.dockerHost.pruneImagesUntil | quote }}
        - name: CRONJOBS
          value: |
            22 1 * * * /lagoon/cronjob.sh "/prune-images.sh"
            22 */4 * * * /lagoon/cronjob.sh "/remove-exited.sh"
            */15 * * * * /lagoon/cronjob.sh "/update-images.sh"
        ports:
        - containerPort: 2375
          protocol: TCP
          name: docker-daemon
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 2375
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 2375
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.dockerHost.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/docker
          name: docker-lib
      {{- with .Values.dockerHost.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.dockerHost.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.dockerHost.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: docker-lib
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.dockerHost.storage.size | quote }}
      {{- with .Values.dockerHost.storage.className }}
      storageClassName: {{ . | quote }}
      {{- end }}
